
name: Heroku Skip Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  heroku:
    if: "contains(github.event.head_commit.message, '[skip heroku]') || contains(github.event.head_commit.message, '[heroku skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Fail CI to skip Heroku deploy
        run: exit 1
